export const VERIFY_ADDRESS_SUCCESS = 'VERIFY_ADDRESS_SUCCESS';
export const REQUEST_ADDRESS_VERIFICATION = 'REQUEST_ADDRESS_VERIFICATION';
export const VERIFY_ADDRESS_FAILURE = 'VERIFY_ADDRESS_FAILURE';
export const FETCH_RATES = 'FETCH_RATES';
export const FETCH_RATES_SUCCESS = 'FETCH_RATES_SUCCESS';
export const FETCH_RATES_FAILURE = 'FETCH_RATES_FAILURE';
